//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json;

namespace ClinicApi.Data_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client : IEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Sessions = new HashSet<Session>();
        }
        
        public string Name { get; set; }
        public string Email { get; set; }
        public System.Guid PsychologistId { get; set; }

        [JsonIgnore]

        public virtual Psychologist Psychologist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Session> Sessions { get; set; }
    }
}
