//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json;

namespace ClinicApi.Data_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session : IEntity
    {
        public System.DateTime BookedDate { get; set; }
        public Type Type { get; set; }
        public System.Guid PsychologistId { get; set; }
        public System.Guid ClientId { get; set; }
    
        [JsonIgnore]
        public virtual Psychologist Psychologist { get; set; }
        [JsonIgnore]
        public virtual Client Client { get; set; }
    }
}
